Modification in style.css file
Chandan-devs-tech/Hello-Microverse pull request #1
Opened 2022-08-25 16:08 UTC by Chandan-devs-tech

2022-08-25 17:30 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @Chandan-devs-tech , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 17:30 UTC, bobb-Rob commented on style.css
> +}
Good job implementing the requirements outlined for this project. However, there are some issues you should take note of. 

- [ ] You did not follow the GitHub flow. All the core requirements for this project should have been implemented in the feature branch, then a pull request showing all things you implement is created. Please read the about [GitHub flow here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md). 
     👉 Kindly implement all the requirements in the feature branch, commit them and push. **_Please note that you do not need to open a new pull request, just push all your commits to this branch and then re-submit for review_**

- [ ] Pull Request(PR) should have a descriptive title describing the changes inside. Also, PR should have a summary describing introduced changes in more detail.  This is best practice as a developer, kindly update this pull request with a suitable title and description

2022-08-25 18:41 UTC, Chandan-devs-tech reviewed
The modification was done in the README.md file while adding a Slack account.

2022-08-25 19:17 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @Chandan-devs-tech , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._
- [REQUIRED ] Please note that the correct use of GitHub flow is fully implemented when all the changes are reflected in a pull request before it is merged with the master/main branch. I noticed that you have the project implementation in you master branch already. Please refer to my [previous review](https://github.com/Chandan-devs-tech/Hello-Microverse/pull/1/files#r955236178) and also read about [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) here and implement accordingly.

     - One way to do this is to manually remove all the files in the master branch and feature branch in GitHub. Then, in your local repo, in the feature branch, push the files and it will reflect in this pull request.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 11:49 UTC, Chandan-devs-tech reviewed
Added mystyle.css  to the index.html file.

2022-08-26 12:34 UTC, ElsonOtake requested changes
STATUS: CHANGES REQUIRED 🟡 

Hi @Chandan-devs-tech, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🥲 🥲 

![woohoo-youre-almost](https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg)

 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Please write short, detailed, easy to understand descriptions of introduced changes to your pull requests. It's a project requirement.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. 👍 👍 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 12:34 UTC, ElsonOtake commented on index.html
> -    <link rel="stylesheet" href="style.css">
- [ ] I think it's better to link your new `mystyle.css` file to `index.htm`. Your new styling does not work without this link.

2022-08-26 12:58 UTC, Chandan-devs-tech commented on index.html
> -    <link rel="stylesheet" href="style.css">
Yaa, I will link the mystyle.css file to index.html.

2022-08-26 13:49 UTC, Chandan-devs-tech reviewed
What?
- I created the required files such as index.html and mystyle.css, .gitignore, test.md, and Set-up Github actions by adding a directory Github/workflows and linters.yml file inside it & other files associated including- .hintrc, .stylelintrc.json to meet the requirements of the project.
- I also changed what the reviewers required too, such as PR description and other optional changes.

Why?
- Due to project requirements and reviewer's ideas.

How?
- Files were created using git bash and edited using vscode and therefore pushed to the Github repository.

2022-08-26 15:26 UTC, Kossi-stack approved these changes
## Status: Approved ✔️
**Hi @Chandan-devs-tech,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 🎉

![](https://user-images.githubusercontent.com/74506933/148243736-d9f63735-4cb1-411f-be28-34972618852d.gif)
You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-08-26 18:45 UTC, merged